package main;

public interface FilesWithData
{
    int DATA_TABLE_ORIGINAL_NUMBER_OF_ROWS = 37203;
    int DATA_TABLE_ORIGINAL_NUMBER_OF_COLS = 83;
    int DATA_TABLE_ORIGINAL_SHEET_INDEX = 0;
    String DATA_TABLE_ORIGINAL_FILEPATH = "data\\VEHICLES_DATASET_ORIGINAL.xlsx";

    int DATA_TABLE_MODIFIED_NUMBER_OF_ROWS = 37203;
    int DATA_TABLE_MODIFIED_NUMBER_OF_COLS = 27;
    int DATA_TABLE_MODIFIED_SHEET_INDEX = 0;
    String DATA_TABLE_MODIFIED_FILEPATH = "data\\VEHICLES_DATASET_MODIFIED.xlsx";
}
